Q1): Retrieve all the records from the Employees table.
A) Select * from Employees

-----------------------------------------------------

Q2): Retrieve the FirstName, LastName, Birthdate, Address, City, and State from the Employees table.

A) Select  FirstName, LastName, Birthdate, Address, City,State from Employees

-----------------------------------------------------

Q3):Retrieve all the columns from the Tracks table, but only return 20 rows.
A) Select * from Tracks Where TrackId<21;